name: App Setup and Output Printer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  app-setup-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run gha-appsetup action
        id: appsetup
        env:
          application_id: ${{ github.repository_id }}
        uses: marcelonyc/gha-appsetup@main
        with:
          application_key: ${{ secrets.application_key }}
          ams_token: ${{ secrets.ams_token }}
          ams_endpoint: ${{ secrets.ams_endpoint }}

      - name: Print all outputs from gha-appsetup
        run: |
          echo "Outputs from gha-appsetup:"
          echo "${{ steps.appsetup.outputs.metadata }}"

          
        shell: bash
