name: App Setup and Output Printer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  app-setup-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run gha-appsetup action
        id: appsetup
        env:
          application_id: ${{ github.repository_id }}
        uses: marcelonyc/gha-appsetup@main
        with:
          application_key: ${{ secrets.application_key }}
          ams_token: ${{ secrets.ams_token }}
          ams_endpoint: ${{ secrets.ams_endpoint }}
        
          
      # - name: Load Repo list into environment
      #   id: repo-values
      #   run: |
      #     echo "Outputs from gha-appsetup:"
      #     for _var in `cat ${{ steps.appsetup.outputs.repo_list }}`
      #     do
      #       echo ${_var} >> "${GITHUB_OUTPUT}"
      #     done
      - name: Get Docker Repository
        id: docker-repo
        run: |
          DOCKER_REPO=$(appconfig docker dev)
          echo "repository=$DOCKER_REPO" >> $GITHUB_OUTPUT
          
      - name: Get repo values
        run: |
          echo "Docker: ${{ steps.docker-repo.outputs.repository }}" 
          
        shell: bash
